# Generated by Django 4.2.3 on 2023-07-22 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_useraccountactivationkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountactivationkey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activation_keys', to=settings.AUTH_USER_MODEL),
        ),
    ]
